spring:
  application:
    name: logparser

langchain4j:
  ollama:
    chat-model:
      base-url: http://localhost:11434
      model-name: llama3.2:1b

server:
  servlet:
    context-path: /logparser/api