apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ollama
spec:
  replicas: {{ .Values.ollama.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ollama
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ollama
    spec:
      containers:
        - name: ollama
          image: "{{ .Values.ollama.image.repository }}:{{ .Values.ollama.image.tag }}"
          ports:
            - containerPort: {{ .Values.ollama.service.port }}
          volumeMounts:
            - mountPath: /root/.ollama
              name: ollama-data
      volumes:
        - name: ollama-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-ollama-pvc